In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from db import get_engine

engine = get_engine()

In [ ]:
print("Python işləyir")

Bankda qalan ve geden müştərilər

In [2]:
df = pd.read_sql("SELECT * FROM gold.churn_summary", engine)

df

   churned   say   faiz
0        0  3992  79.84
1        1  1008  20.16

In [4]:
aktivlik_report = pd.read_sql(
    "SELECT * FROM gold.churn_by_activity",
    engine
)

aktivlik_report

      Aktivlik  Müştəri sayı  Bankı tərk edənlər  Churn faizi
0  Aktiv deyil          2029                 584        28.78
1     Aktivdir          2971                 424        14.27

aktiv olmayan müştərilərdə churn faizi təxminən 2 dəfə yüksəkdir.

In [6]:
products_report = pd.read_sql(
    "SELECT * FROM gold.churn_by_products",
    engine
)

products_report

   Məhsul sayı  Müştəri sayı  Bankı tərk edənlər  Churn faizi
0            1          2289                 520        22.72
1            2          2114                 214        10.12
2            3           441                 171        38.78
3            4           156                 103        66.03

4 mehsulu olan daha cox gedib/

In [10]:
churn_products_activity_df = pd.read_sql(
    "SELECT * FROM gold.churn_products_activity",
    engine
)

churn_products_activity_df

   products_count  is_active   say  gedən  churn_faizi
0               1          0  1037    328        31.63
1               1          1  1252    192        15.34
2               2          0   787    133        16.90
3               2          1  1327     81         6.10
4               3          0   146     75        51.37
5               3          1   295     96        32.54
6               4          0    59     48        81.36
7               4          1    97     55        56.70

Görünür məhsul sayı 3 4 olan müştərilərin tərk etməsi daha çoxdur

In [12]:
emeliyyat_report = pd.read_sql(
    "SELECT * FROM gold.churn_by_transactions",
    engine
)

emeliyyat_report

   Churn  Müştəri sayı  Orta əməliyyat sayı  Median əməliyyat sayı
0      0          3992                16.59                   19.0
1      1          1008                11.09                    8.0

gedən müştərilər orta hesabla 33% daha az əməliyyat aparıblar.

In [14]:
kanal_report = pd.read_sql(
    "SELECT * FROM gold.churn_by_channel",
    engine
)

kanal_report

          Kanal  Qalanlar (%)  Gedənlər (%)
0           ATM         18.72         19.40
1        Filial          9.65         10.83
2  Mobil t?tbiq         43.70         41.76
3           POS         27.92         28.01

Müştərilərin bankı tərk etməsini izah etmək üçün kanal seçimi güclü göstərici kimi görünmür.

---------------------------------------------------------------------------------------

In [ ]:
print("Python işləyir")